name: Build Console App
on:
  workflow_dispatch:
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-12, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: |
          dotnet restore JboxWebdav.ConsoleApp/JboxWebdav.ConsoleApp.csproj
          dotnet build JboxWebdav.ConsoleApp/JboxWebdav.ConsoleApp.csproj -c Release -f net6.0 --no-restore -a x64
          dotnet build JboxWebdav.ConsoleApp/JboxWebdav.ConsoleApp.csproj -c Release -f net6.0 --no-restore -a arm64

      - name: Build for macOS
        if: matrix.os == 'macos-12'
        run: |
          dotnet restore JboxWebdav.ConsoleApp/JboxWebdav.ConsoleApp.csproj
          dotnet build JboxWebdav.ConsoleApp/JboxWebdav.ConsoleApp.csproj -c Release -f net6.0 --no-restore -a x64
          dotnet build JboxWebdav.ConsoleApp/JboxWebdav.ConsoleApp.csproj -c Release -f net6.0 --no-restore -a arm64

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          dotnet restore JboxWebdav.ConsoleApp/JboxWebdav.ConsoleApp.csproj
          dotnet build JboxWebdav.ConsoleApp/JboxWebdav.ConsoleApp.csproj -c Release -f net6.0 --no-restore -a x64
          dotnet build JboxWebdav.ConsoleApp/JboxWebdav.ConsoleApp.csproj -c Release -f net6.0 --no-restore -a arm64

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ matrix.os }}
          if-no-files-found: error
          path: |
            JboxWebdav.ConsoleApp/bin/Release/*.*